#--------------------------------------------------------------------------
# This config file is used by ../bin/export-palette-scss.js to export the
# ./badger-css-palette.json file into SCSS files in styles/config/palette
# It is usually invoked by running `pnpm build:palette` which is an alias
# for `bin/export-palette-scss.js -c config/export-palette-scss.yaml -v`.
#--------------------------------------------------------------------------

# Path to palette data file (downloaded from badger-color)
palette:    config/badger-css-palette.json
# Path to output directory
output:     styles/color
# Default brand color
brandColor: blue

# These are the defaults, but you can tweak them...
# semanticColors:
#   info:     blue
#   success:  green
#   warning:  orange
#   error:    red
#   focus:    blue
#   valid:    green
#   invalid:  red
#
# selectors:
#   info:     .info
#   success:  .success
#   warning:  .warning
#   error:    .error
#   focus:
#     - .focus:not(button):not(.button)
#     - :focus:not(button):not(.button)
#     - .field:has(:focus)
#     - label:is(.checkbox, .radio, :has(input[type=checkbox]), :has(input[type=radio])):is(:has(:focus))
#   valid:
#     - .field.valid
#     - .field.valid :focus:not(button):not(.button)
#     - .field.valid:has(:focus)
#     - .field.valid:has(:focus) label:is(.checkbox, .radio, :has(input[type=checkbox]), :has(input[type=radio])):is(:has(:focus))
#   invalid:
#     - .field.invalid
#     - .field.invalid :focus:not(button):not(.button)
#     - .field.invalid:has(:focus)
#     - .field.invalid:has(:focus) label:is(.checkbox, .radio, :has(input[type=checkbox]), :has(input[type=radio])):is(:has(:focus))
