palette:    config/badger-css-palette.json
output:     styles/config/palette
brandColor: violet
colorScopes:
  blue:   '.info, .focus:not(button):not(.button), :focus:not(button):not(.button), .field:has(:focus), label.checkbox:has(:focus), label.radio:has(:focus)'
  green:  '.success, .valid, .valid :focus'
  orange: '.warning'
  red:    '.error, .invalid, .invalid :focus'
